### PR TITLE
binutils: drop Edison fix

### PR DESCRIPTION
**Pull request by pohly**
Upstream OE-core now includes a fix for this and the one we have locally
no longer applies, so we need to remove it.

[skip ci]

### CODE REVIEW

**Comment by pohly** [comment]
@jlaako please review and confirm that the binutils patch is included in OE-core.

We have a problem with merging this, though - once we merge it, all further testing against meta-ostro-fixes will fail on Edison because currently the fix is still needed. So we have to keep that time interval short.

I added "[skip ci]" because testing this patch is useless and harmful for the Edison test machines (?).

**Comment by jlaako** [comment]
You should first merge upstream changes that contain the fix, otherwise flashing Edison with intermediate build will result in need for recovery actions (bricked device).

**Comment by mythi** [comment]
Thanks for letting us know. Need to think how to do the integration as "merge upstream changes first" won't work. This PR and the upstream changes are needed simultaneously to get a good build.

**Comment by jlaako** [comment]
If you combine both this layer and upstream layer updates in single combo-layer tool run you get atomic update on main Ostro combo repo that doesn't break anything?

**Comment by pohly** [comment]
On Tue, 2016-03-08 at 03:52 -0800, Jussi Laako wrote:

> If you combine both this layer and upstream layer updates in single
> combo-layer tool run you get atomic update on main Ostro combo repo
> that doesn't break anything?

Yes, one can get atomic commits to ostro-os this way.

However, there's a problem directly after merging this PR: any other
pending (or future) PRs for meta-ostro-fixes will get retested without
the Edison fix and thus would break the test hardware.

One has to be careful to not have pending PRs and tell everyone else to
not submit something until ostro-os master also got updated (which can't
be immediately, because the combined PR still needs to be tested).

**Comment by mythi** [comment]
pushed in master.

**Pull request closed without merging**
